### ISSUE TITLE
Install pods for firebase.

### ISSUE THREAD

**Issue by nikhilagr** [nikhilagr/Colab#2]
Install pods in the mobile client [refer this link](https://firebase.google.com/docs/ios/setup)
- [x] Install pods for 'Firebase/Core'
- [x] Install pods for 'Firebase/Messaging'
- [x] Install pods for 'Firebase/Auth' 
- [x] Install pods for 'Firebase/Firestore'

**Comment by VishwajeetKharote** [comment]
Installed all the pods

**Comment by nikhilagr** [comment]
Great!!
